

IDD_SFX_SOUNDEXPANDER_SETTINGS_DIALOG DIALOG DISCARDABLE 0, 0, 180, 110
BEGIN
    AUTOCHECKBOX    "", IDC_SFX_SOUNDEXPANDER_ENABLE,
                    7, 7, 99, 10, BS_AUTOCHECKBOX | WS_TABSTOP
    LTEXT           "", IDC_SFX_SOUNDEXPANDER_TYPE_LABEL,
                    9, 24, 30, 8
    COMBOBOX        IDC_SFX_SOUNDEXPANDER_TYPE,
                    45, 22, 100, 80, CBS_DROPDOWNLIST | WS_VSCROLL | WS_TABSTOP

    DEFPUSHBUTTON   "", IDOK,
                    30, 90, 50, 14, WS_TABSTOP
    PUSHBUTTON      "", IDCANCEL,
                    90, 90, 50, 14, WS_TABSTOP
END




IDD_MASCUERADE_SFX_SOUNDEXPANDER_SETTINGS_DIALOG DIALOG DISCARDABLE 0, 0, 180, 110
BEGIN
    AUTOCHECKBOX    "", IDC_SFX_SOUNDEXPANDER_ENABLE,
                    7, 7, 99, 10, BS_AUTOCHECKBOX | WS_TABSTOP
    LTEXT           "", IDC_SFX_SOUNDEXPANDER_TYPE_LABEL,
                    9, 24, 30, 8
    COMBOBOX        IDC_SFX_SOUNDEXPANDER_TYPE,
                    45, 22, 100, 80, CBS_DROPDOWNLIST | WS_VSCROLL | WS_TABSTOP
    AUTOCHECKBOX    "", IDC_SFX_SOUNDEXPANDER_IO_SWAP,
                    7, 40, 110, 10, BS_AUTOCHECKBOX | WS_TABSTOP

    DEFPUSHBUTTON   "", IDOK,
                    30, 90, 50, 14, WS_TABSTOP
    PUSHBUTTON      "", IDCANCEL,
                    90, 90, 50, 14, WS_TABSTOP
END



STRINGTABLE
BEGIN
    IDS_SFX_SOUNDEXPANDER_CAPTION N_("SFX Sound Expander settings")
    IDS_SFX_SOUNDEXPANDER_ENABLE  N_("Enable the SFX Sound Expander cartridge")
    IDS_SFX_SOUNDEXPANDER_TYPE    N_("YM chip type")
END



STRINGTABLE
LANGUAGE LANG_DANISH, SUBLANG_NEUTRAL
BEGIN
    IDS_SFX_SOUNDEXPANDER_CAPTION "SFX Sound Expander-indstillinger"
    IDS_SFX_SOUNDEXPANDER_ENABLE  "Aktivér SFX sound Expander cartridget"
    IDS_SFX_SOUNDEXPANDER_TYPE    "YM chiptype"
END



STRINGTABLE
LANGUAGE LANG_GERMAN, SUBLANG_NEUTRAL
BEGIN
    IDS_SFX_SOUNDEXPANDER_CAPTION "SFX Sound Expander Einstellungen"
    IDS_SFX_SOUNDEXPANDER_ENABLE  "SFX Soundexpander Modul aktivieren"
    IDS_SFX_SOUNDEXPANDER_TYPE    "YM Chip Typ"
END



STRINGTABLE
LANGUAGE LANG_SPANISH, SUBLANG_NEUTRAL
BEGIN
    IDS_SFX_SOUNDEXPANDER_CAPTION "Ajustes SFX Sound Expander"
    IDS_SFX_SOUNDEXPANDER_ENABLE  "Permitir cartucho SFX Sound Expander"
    IDS_SFX_SOUNDEXPANDER_TYPE    "Tipo de chip YM"
END



STRINGTABLE
LANGUAGE LANG_FRENCH, SUBLANG_NEUTRAL
BEGIN
    IDS_SFX_SOUNDEXPANDER_CAPTION "Paramètres du SFX Sound Expander"
    IDS_SFX_SOUNDEXPANDER_ENABLE  "Activer la cartouche SFX Sound Expander"
    IDS_SFX_SOUNDEXPANDER_TYPE    "Type de puce YM"
END



#ifndef WINDRES_CP_IGNORE
#pragma code_page(28592)
#endif
STRINGTABLE
LANGUAGE LANG_HUNGARIAN, SUBLANG_NEUTRAL
BEGIN
    IDS_SFX_SOUNDEXPANDER_CAPTION "SFX Sound Expander settings"
    IDS_SFX_SOUNDEXPANDER_ENABLE  "Enable the SFX Sound Expander cartridge"
    IDS_SFX_SOUNDEXPANDER_TYPE    "YM chip típusa"
END
#ifndef WINDRES_CP_IGNORE
#pragma code_page(28591)
#endif



STRINGTABLE
LANGUAGE LANG_ITALIAN, SUBLANG_NEUTRAL
BEGIN
    IDS_SFX_SOUNDEXPANDER_CAPTION "Impostazioni SFX Sound Expander"
    IDS_SFX_SOUNDEXPANDER_ENABLE  "Attiva cartuccia SFX Sound Expander"
    IDS_SFX_SOUNDEXPANDER_TYPE    "Tipo chip YM"
END



#ifndef WINDRES_CP_IGNORE
#pragma code_page(949)
#endif
STRINGTABLE
LANGUAGE LANG_KOREAN, SUBLANG_NEUTRAL
BEGIN
    IDS_SFX_SOUNDEXPANDER_CAPTION "SFX Sound Expander ¼³Á¤"
    IDS_SFX_SOUNDEXPANDER_ENABLE  "Enable the SFX Sound Expander cartridge"
    IDS_SFX_SOUNDEXPANDER_TYPE    "YM Ä¨ Á¾·ù"
END
#ifndef WINDRES_CP_IGNORE
#pragma code_page(28591)
#endif



STRINGTABLE
LANGUAGE LANG_DUTCH, SUBLANG_NEUTRAL
BEGIN
    IDS_SFX_SOUNDEXPANDER_CAPTION "SFX Sound Expander instellingen"
    IDS_SFX_SOUNDEXPANDER_ENABLE  "Activeer de SFX Sound Expander cartridge"
    IDS_SFX_SOUNDEXPANDER_TYPE    "YM chip model"
END



#ifndef WINDRES_CP_IGNORE
#pragma code_page(28592)
#endif
STRINGTABLE
LANGUAGE LANG_POLISH, SUBLANG_NEUTRAL
BEGIN
    IDS_SFX_SOUNDEXPANDER_CAPTION "Ustawienia SFX Sound Expander"
    IDS_SFX_SOUNDEXPANDER_ENABLE  "W³±cz kartrid¿ SFX Sound Expander"
    IDS_SFX_SOUNDEXPANDER_TYPE    "Typ uk³adu YM"
END
#ifndef WINDRES_CP_IGNORE
#pragma code_page(28591)
#endif



#ifndef WINDRES_CP_IGNORE
#pragma code_page(28595)
#endif
STRINGTABLE
LANGUAGE LANG_RUSSIAN, SUBLANG_NEUTRAL
BEGIN
    IDS_SFX_SOUNDEXPANDER_CAPTION "SFX Sound Expander settings"
    IDS_SFX_SOUNDEXPANDER_ENABLE  "Enable the SFX Sound Expander cartridge"
    IDS_SFX_SOUNDEXPANDER_TYPE    "YM chip type"
END
#ifndef WINDRES_CP_IGNORE
#pragma code_page(28591)
#endif



STRINGTABLE
LANGUAGE LANG_SWEDISH, SUBLANG_NEUTRAL
BEGIN
    IDS_SFX_SOUNDEXPANDER_CAPTION "Inställningar för SFX Sound Expander"
    IDS_SFX_SOUNDEXPANDER_ENABLE  "Aktivera SFX Sound Expander-insticksmodul"
    IDS_SFX_SOUNDEXPANDER_TYPE    "YM-kretstyp"
END



#ifndef WINDRES_CP_IGNORE
#pragma code_page(28599)
#endif
STRINGTABLE
LANGUAGE LANG_TURKISH, SUBLANG_NEUTRAL
BEGIN
    IDS_SFX_SOUNDEXPANDER_CAPTION "SFX Sound Expander Ayarlarý"
    IDS_SFX_SOUNDEXPANDER_ENABLE  "SFX Sound Expander kartuþunu aktif et"
    IDS_SFX_SOUNDEXPANDER_TYPE    "YM çip tipi"
END
#ifndef WINDRES_CP_IGNORE
#pragma code_page(28591)
#endif


