

IDD_SFX_SOUNDSAMPLER_SETTINGS_DIALOG DIALOG DISCARDABLE 0, 0, 180, 110
BEGIN
    AUTOCHECKBOX    "", IDC_SFX_SOUNDSAMPLER_ENABLE,
                    7, 7, 110, 10, BS_AUTOCHECKBOX | WS_TABSTOP
    AUTOCHECKBOX    "", IDC_SFX_SOUNDSAMPLER_IO_SWAP,
                    7, 22, 110, 10, BS_AUTOCHECKBOX | WS_TABSTOP

    DEFPUSHBUTTON   "", IDOK,
                    30, 90, 50, 14, WS_TABSTOP
    PUSHBUTTON      "", IDCANCEL,
                    90, 90, 50, 14, WS_TABSTOP
END



STRINGTABLE
BEGIN
    IDS_SFX_SOUNDSAMPLER_CAPTION N_("SFX Sound Sampler settings")
    IDS_SFX_SOUNDSAMPLER_ENABLE  N_("Enable the SFX Sound Sampler cartridge")
END



STRINGTABLE
LANGUAGE LANG_DANISH, SUBLANG_NEUTRAL
BEGIN
    IDS_SFX_SOUNDSAMPLER_CAPTION "SFX Sound Sampler-indstillinger"
    IDS_SFX_SOUNDSAMPLER_ENABLE  "Aktivér SFX Sound Sampler cartridge"
END



STRINGTABLE
LANGUAGE LANG_GERMAN, SUBLANG_NEUTRAL
BEGIN
    IDS_SFX_SOUNDSAMPLER_CAPTION "SFX Sound Sampler Einstellungen"
    IDS_SFX_SOUNDSAMPLER_ENABLE  "SFX Sound Sampler Modul aktivieren"
END



STRINGTABLE
LANGUAGE LANG_SPANISH, SUBLANG_NEUTRAL
BEGIN
    IDS_SFX_SOUNDSAMPLER_CAPTION "Ajustes SFX Sound Sampler"
    IDS_SFX_SOUNDSAMPLER_ENABLE  "Permitir cartucho SFX Sound Sampler"
END



STRINGTABLE
LANGUAGE LANG_FRENCH, SUBLANG_NEUTRAL
BEGIN
    IDS_SFX_SOUNDSAMPLER_CAPTION "Paramètres du SFX Sound Sampler"
    IDS_SFX_SOUNDSAMPLER_ENABLE  "Activer la cartouche SFX Sound Sampler"
END



#ifndef WINDRES_CP_IGNORE
#pragma code_page(28592)
#endif
STRINGTABLE
LANGUAGE LANG_HUNGARIAN, SUBLANG_NEUTRAL
BEGIN
    IDS_SFX_SOUNDSAMPLER_CAPTION "SFX Sound Sampler settings"
    IDS_SFX_SOUNDSAMPLER_ENABLE  "SFX Sound Sampler engedélyezése"
END
#ifndef WINDRES_CP_IGNORE
#pragma code_page(28591)
#endif



STRINGTABLE
LANGUAGE LANG_ITALIAN, SUBLANG_NEUTRAL
BEGIN
    IDS_SFX_SOUNDSAMPLER_CAPTION "Impostazioni SFX Sound Sampler"
    IDS_SFX_SOUNDSAMPLER_ENABLE  "Attiva cartuccia SFX Sound Sampler"
END



#ifndef WINDRES_CP_IGNORE
#pragma code_page(949)
#endif
STRINGTABLE
LANGUAGE LANG_KOREAN, SUBLANG_NEUTRAL
BEGIN
    IDS_SFX_SOUNDSAMPLER_CAPTION "SFX Sound Sampler settings"
    IDS_SFX_SOUNDSAMPLER_ENABLE  "SFX Sound Sampler Ä«Æ®¸®Áö ¸¦ ÀÛµ¿½ÃÅ²´Ù"
END
#ifndef WINDRES_CP_IGNORE
#pragma code_page(28591)
#endif



STRINGTABLE
LANGUAGE LANG_DUTCH, SUBLANG_NEUTRAL
BEGIN
    IDS_SFX_SOUNDSAMPLER_CAPTION "SFX Sound Sampler instellingen"
    IDS_SFX_SOUNDSAMPLER_ENABLE  "Activeer de SFX Sound Sampler cartridge"
END



#ifndef WINDRES_CP_IGNORE
#pragma code_page(28592)
#endif
STRINGTABLE
LANGUAGE LANG_POLISH, SUBLANG_NEUTRAL
BEGIN
    IDS_SFX_SOUNDSAMPLER_CAPTION "Ustawienia samplera d¼wiêku SFX"
    IDS_SFX_SOUNDSAMPLER_ENABLE  "W³±cz kartrid¿ SFX Sound Sampler"
END
#ifndef WINDRES_CP_IGNORE
#pragma code_page(28591)
#endif



#ifndef WINDRES_CP_IGNORE
#pragma code_page(28595)
#endif
STRINGTABLE
LANGUAGE LANG_RUSSIAN, SUBLANG_NEUTRAL
BEGIN
    IDS_SFX_SOUNDSAMPLER_CAPTION "SFX Sound Sampler settings"
    IDS_SFX_SOUNDSAMPLER_ENABLE  "Enable the SFX Sound Sampler cartridge"
END
#ifndef WINDRES_CP_IGNORE
#pragma code_page(28591)
#endif



STRINGTABLE
LANGUAGE LANG_SWEDISH, SUBLANG_NEUTRAL
BEGIN
    IDS_SFX_SOUNDSAMPLER_CAPTION "Inställningar för SFX Sound Sampler"
    IDS_SFX_SOUNDSAMPLER_ENABLE  "Aktivera SFX Sound Sampler-insticksmodul"
END



#ifndef WINDRES_CP_IGNORE
#pragma code_page(28599)
#endif
STRINGTABLE
LANGUAGE LANG_TURKISH, SUBLANG_NEUTRAL
BEGIN
    IDS_SFX_SOUNDSAMPLER_CAPTION "SFX Sound Sampler ayarlarý"
    IDS_SFX_SOUNDSAMPLER_ENABLE  "SFX Sound Sampler kartuþunu aktif et"
END
#ifndef WINDRES_CP_IGNORE
#pragma code_page(28591)
#endif


