
#include "vice.h"

#include "res.h"
#include "rescommon.h"

#ifndef WINDRES_CP_IGNORE
#pragma code_page(28591)
#endif


IDD_TFE_SETTINGS_DIALOG DIALOG DISCARDABLE 0, 0, 270, 100
BEGIN
    LTEXT         "", IDC_TFE_SETTINGS_ENABLE_T,
                  9, 7, 30, 8
    COMBOBOX      IDC_TFE_SETTINGS_ENABLE,
                  45, 5, 50, 80, CBS_DROPDOWNLIST | WS_VSCROLL | WS_TABSTOP
    LTEXT         "", IDC_TFE_SETTINGS_INTERFACE_T,
                  9, 24, 30, 8
    COMBOBOX      IDC_TFE_SETTINGS_INTERFACE,
                  45, 22, 200, 80, CBS_DROPDOWNLIST | WS_VSCROLL | WS_TABSTOP
    LTEXT         "", IDC_TFE_SETTINGS_INTERFACE_NAME,
                  9, 44, 250, 8
    LTEXT         "", IDC_TFE_SETTINGS_INTERFACE_DESC,
                  9, 60, 250, 8
    DEFPUSHBUTTON "", IDOK,
                  20, 75, 50, 14, WS_TABSTOP
    PUSHBUTTON    "", IDCANCEL,
                  80, 75, 50, 14, WS_TABSTOP
END



IDD_MASCUERADE_TFE_SETTINGS_DIALOG DIALOG DISCARDABLE 0, 0, 270, 116
BEGIN
    LTEXT         "", IDC_TFE_SETTINGS_ENABLE_T,
                  9, 7, 30, 8
    COMBOBOX      IDC_TFE_SETTINGS_ENABLE,
                  45, 5, 50, 80, CBS_DROPDOWNLIST | WS_VSCROLL | WS_TABSTOP
    AUTOCHECKBOX  "", IDC_TFE_SETTINGS_IO_SWAP,
                  7, 21, 120, 10, BS_AUTOCHECKBOX | WS_TABSTOP
    LTEXT         "", IDC_TFE_SETTINGS_INTERFACE_T,
                  9, 40, 30, 8
    COMBOBOX      IDC_TFE_SETTINGS_INTERFACE,
                  45, 38, 200, 80, CBS_DROPDOWNLIST | WS_VSCROLL | WS_TABSTOP
    LTEXT         "", IDC_TFE_SETTINGS_INTERFACE_NAME,
                  9, 60, 250, 8
    LTEXT         "", IDC_TFE_SETTINGS_INTERFACE_DESC,
                  9, 76, 250, 8

    DEFPUSHBUTTON "", IDOK,
                  20, 91, 50, 14, WS_TABSTOP
    PUSHBUTTON    "", IDCANCEL,
                  80, 91, 50, 14, WS_TABSTOP
END



STRINGTABLE
BEGIN
    IDS_TFE_CAPTION   N_("Ethernet settings")
    IDS_TFE_ETHERNET  N_("Ethernet")
    IDS_TFE_INTERFACE N_("Interface")
END



STRINGTABLE
LANGUAGE LANG_DANISH, SUBLANG_NEUTRAL
BEGIN
    IDS_TFE_CAPTION   "Ethernetindstillinger"
    IDS_TFE_ETHERNET  "Ethernet"
    IDS_TFE_INTERFACE "Interface"
END



STRINGTABLE
LANGUAGE LANG_GERMAN, SUBLANG_NEUTRAL
BEGIN
    IDS_TFE_CAPTION   "Ethernet Einstellungen"
    IDS_TFE_ETHERNET  "Ethernet"
    IDS_TFE_INTERFACE "Schnittstelle"
END



STRINGTABLE
LANGUAGE LANG_SPANISH, SUBLANG_NEUTRAL
BEGIN
    IDS_TFE_CAPTION   "Ajustes Ethernet"
    IDS_TFE_ETHERNET  "Ethernet"
    IDS_TFE_INTERFACE "Interface"
END



STRINGTABLE
LANGUAGE LANG_FRENCH, SUBLANG_NEUTRAL
BEGIN
    IDS_TFE_CAPTION   "ParamËtres Ethernet"
    IDS_TFE_ETHERNET  "Ethernet"
    IDS_TFE_INTERFACE "Interface"
END



#ifndef WINDRES_CP_IGNORE
#pragma code_page(28592)
#endif
STRINGTABLE
LANGUAGE LANG_HUNGARIAN, SUBLANG_NEUTRAL
BEGIN
    IDS_TFE_CAPTION   "Ethernet settings"
    IDS_TFE_ETHERNET  "Ethernet"
    IDS_TFE_INTERFACE "Interface"
END
#ifndef WINDRES_CP_IGNORE
#pragma code_page(28591)
#endif



STRINGTABLE
LANGUAGE LANG_ITALIAN, SUBLANG_NEUTRAL
BEGIN
    IDS_TFE_CAPTION   "Impostazioni Ethernet"
    IDS_TFE_ETHERNET  "Ethernet"
    IDS_TFE_INTERFACE "Interfaccia"
END



#ifndef WINDRES_CP_IGNORE
#pragma code_page(949)
#endif
STRINGTABLE
LANGUAGE LANG_KOREAN, SUBLANG_NEUTRAL
BEGIN
    IDS_TFE_CAPTION   "¿Ã¥ı≥› º≥¡§"
    IDS_TFE_ETHERNET  "¿Ã¥ı≥›"
    IDS_TFE_INTERFACE "¿Œ≈Õ∆‰¿ÃΩ∫"
END
#ifndef WINDRES_CP_IGNORE
#pragma code_page(28591)
#endif



STRINGTABLE
LANGUAGE LANG_DUTCH, SUBLANG_NEUTRAL
BEGIN
    IDS_TFE_CAPTION   "Ethernet instellingen"
    IDS_TFE_ETHERNET  "Ethernet"
    IDS_TFE_INTERFACE "Interface"
END



#ifndef WINDRES_CP_IGNORE
#pragma code_page(28592)
#endif
STRINGTABLE
LANGUAGE LANG_POLISH, SUBLANG_NEUTRAL
BEGIN
    IDS_TFE_CAPTION   "Ustawienia Ethernet"
    IDS_TFE_ETHERNET  "Ethernet"
    IDS_TFE_INTERFACE "Interfejs"
END
#ifndef WINDRES_CP_IGNORE
#pragma code_page(28591)
#endif



#ifndef WINDRES_CP_IGNORE
#pragma code_page(28595)
#endif
STRINGTABLE
LANGUAGE LANG_RUSSIAN, SUBLANG_NEUTRAL
BEGIN
    IDS_TFE_CAPTION   "Ethernet settings"
    IDS_TFE_ETHERNET  "Ethernet"
    IDS_TFE_INTERFACE "Interface"
END
#ifndef WINDRES_CP_IGNORE
#pragma code_page(28591)
#endif



STRINGTABLE
LANGUAGE LANG_SWEDISH, SUBLANG_NEUTRAL
BEGIN
    IDS_TFE_CAPTION   "Ethernetinst‰llningar"
    IDS_TFE_ETHERNET  "Ethernet"
    IDS_TFE_INTERFACE "Gr‰nssnitt"
END



#ifndef WINDRES_CP_IGNORE
#pragma code_page(28599)
#endif
STRINGTABLE
LANGUAGE LANG_TURKISH, SUBLANG_NEUTRAL
BEGIN
    IDS_TFE_CAPTION   "Ethernet Ayarlar˝"
    IDS_TFE_ETHERNET  "Ethernet"
    IDS_TFE_INTERFACE "Arabirim"
END
#ifndef WINDRES_CP_IGNORE
#pragma code_page(28591)
#endif


